apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation-vs
spec:
  hosts:
  - recommendation-svc
  http:
  - route:
    - destination:
        host: recommendation-svc
    timeout: 1.000s
