apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.4
  mode: ClusterWide
  tracing:
    type: Jaeger
    sampling: 10000
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
  # Run the control plane on the infrastructure nodes
  # 
  #runtime:
  #  defaults:
  #    pod:
  #      nodeSelector: 
  #        node-role.kubernetes.io/infra: ""
  #      tolerations: 
  #      - effect: NoSchedule
  #        key: node-role.kubernetes.io/infra
  #        value: reserved
  #      - effect: NoExecute
  #        key: node-role.kubernetes.io/infra
  #        value: reserved