apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.4
  mode: ClusterWide
  tracing:
    type: Jaeger
    sampling: 10000
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          elasticsearch:
            nodeCount: 1
            redundancyPolicy: SingleRedundancy
          type: Elasticsearch
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod