apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  # This can be based on selectors (like this yaml) or based on namespaces(example below)
  #members:
  #  - istio-demo
  #  - another-project
  memberSelectors:
    #Namespace Labels
    - matchLabels:
        istio-injection: enabled