apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    # Since we are disabling the version tag, this will pick all versions in roundrobin
    app: recommendation    
    #version: v1